### ISSUE TITLE
Calling non-static methods

### ISSUE THREAD

**Issue by jruvinski** [Mecanik/ZF3Turbo#1]
Some non-static methods are been called from Listener/ZF3TurboListener.php
They are:
Engine/ZF3TurboCSSEngine::minify_css_callback();
Engine/ZF3TurboJSEngine::minify_js_callback();
Engine/ZF3TurboJSEngine::removeComments();
Engine/ZF3TurboHTMLEngine::remove_comments_callback();

Maybe some more can be with this warning, these was what I identify.

Edit: I would have made a pull request, but apparently I don't have permission.

**Comment by Mecanik** [comment]
Yes it's not 100% finished. I did not have time and I will continue soon.

Feel free to add fixes 👍 

Edit: Added you as a collaborator.
